### ISSUE TITLE
.cache/furaffinity-dl/fa-dl.DLrzxIBHoJ: No such file or directory (cygwin) [win7]

### ISSUE THREAD

**Issue by tehgarra** [Shnatsel/furaffinity-dl#13]
Everything else seems to work fine up until this point in the program and i'm left with nothing

i don't know much but apparently whatever directory and file that's supposed to be created isn't being created...

i'll download a distro or something and try it on that in the meantime

**Comment by tehgarra** [comment]
+ set -e
+ '[' gallery/kodardragon = '' ']'
+ '[' gallery/kodardragon = -h ']'
+ '[' gallery/kodardragon = --help ']'
+ runtime_dir=/home/pilot0/.cache/furaffinity-dl
+ mkdir -p /home/pilot0/.cache/furaffinity-dl
++ umask u=rwx,g=,o=
++ mktemp /home/pilot0/.cache/furaffinity-dl/fa-dl.XXXXXXXXXX
+ tempfile=/home/pilot0/.cache/furaffinity-dl/fa-dl.dg3NXzyZGR
+ trap cleanup EXIT
+ COOKIES_FILE=
+ '[' '' = '' ']'
+ url=https://www.furaffinity.net/gallery/kodardragon
+ true
+ fwget -O /home/pilot0/.cache/furaffinity-dl/fa-dl.dg3NXzyZGR https://www.furaffinity.net/gallery/kodardragon
+ wget '--user-agent=Mozilla/5.0 furaffinity-dl (https://github.com/Shnatsel/furaffinity-dl)' -O /home/pilot0/.cache/furaffinity-dl/fa-dl.dg3NXzyZGR https://www.furaffinity.net/gallery/kodardragon
/home/pilot0/.cache/furaffinity-dl/fa-dl.dg3NXzyZGR: No such file or directory
+ cleanup
+ rm -r /home/pilot0/.cache/furaffinity-dl/fa-dl.dg3NXzyZGR

works fine on lubuntu as expected, but no success on cygwin.

**Comment by Shnatsel** [comment]
Thanks a lot for the trace!

Sadly, it clearly shows `mkdir -p /home/pilot0/.cache/furaffinity-dl` followed by "No such file or directory" on creating a file in that folder. In a sane unix environment this should never, ever happen.

Given how I keep reaping karma off a stackoverflow answer to "[how do I make HTTPS downloads work in cygwin](https://stackoverflow.com/a/15252756/585725)", setting up a Cygwin environment so that it actually works is too much trouble for me to recommend it as a reasonable option to furaffinity-dl users. I'll document that in the README.

Booting Linux from a USB stick is a much more straightforward, and that's what I'd recommend in your case. Linux in a VM works too, but it's harder to get files back to windows, while when booting from USB you can write them directly to your Windows partition.
